# A Service is a higher-level resource that provides network access to a set of replica Pods
# allowing them to communicate with each other and with external clients.
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-nodeport
  labels:
    app: admin-dashboard
spec:
  # Using a NodePort gives you the freedom to set up your own load balancing solution, to configure environments that are
  # not fully supported by Kubernetes, or even to expose one or more nodes' IP addresses directly.
  type: NodePort
  # Select all pods with label app: admin-dashboard
  selector:
    app: admin-dashboard
  ports:
    # The port number on which the Service listens for incoming traffic
    - port: 80
      # Listens using TCP Protocol
      protocol: TCP
      # The port number on which the application running inside the Pods is listening and ready to receive traffic.
      # When a client sends traffic to the Service's port, the traffic is forwarded to one of the Pods in the deployment.
      # The traffic is then directed to the Pod's targetPort,
      targetPort: 80 # The port exposed in the admin-dashboard pod's containers
      # nodePort is the port exposed EXTERNALLY. It maps to the deployment port (80), and then to the port exposed by the pods (7878)
      nodePort: 30001
