name: Deployment to Okteto
on:
  push:
    branches:
      - main
jobs:
  okteto-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: Create devlopment environments namespace
        uses: okteto/namespace@latest
        with:
          namespace: prod2-szwtomas
      
      - name: Build image and deploy 
        uses: ./.github/actions
        with:
          tag: okteto.dev/admin-dashboard:${{ github.sha }}
          file: prod2.Dockerfile
          sha: ${{ github.sha }}
          okteto_yml: okteto.yml
          k8s_deployment_file: kubernetes/deployment.yml
